/**
 * @file init.hpp
 * @brief STM32H750 bare-metal system initialization
 *
 * Configures the STM32H7 clock tree for 480 MHz operation using HSE.
 * No HAL dependencies - uses SVD-generated register definitions.
 */
#ifndef SBL_HW_DRIVER_INIT_HPP_
#define SBL_HW_DRIVER_INIT_HPP_

#include <cstdint>
#include <sbl/hw/reg/rcc.hpp>
#include <sbl/hw/reg/pwr.hpp>
#include <sbl/hw/reg/flash.hpp>
#include <sbl/hw/reg/gpio.hpp>
#include <sbl/hw/reg/cortex_m.hpp>
#include <sbl/hw/reg/usb_otg.hpp>
#include <sbl/hw/reg/irq.hpp>
#include <sbl/hw/reg/sai.hpp>
#include "timer.hpp"
#include "timeout.hpp"

// SystemCoreClock - required by TinyUSB and other CMSIS-compatible code
// Updated by init() when clock configuration changes
extern "C" {
inline uint32_t SystemCoreClock = 64'000'000;  // Default to HSI
}

namespace sbl::driver {

/**
 * @brief Clock configuration for STM32H750
 */
struct ClockConfig {
    uint32_t hse_mhz = 16;       // External oscillator (Daisy Seed: 16 MHz)
    uint32_t sysclk_mhz = 480;   // Target SYSCLK
    uint32_t hclk_mhz = 240;     // AHB clock (SYSCLK/2 max for D1)
    uint32_t pclk1_mhz = 120;    // APB1 clock
    uint32_t pclk2_mhz = 120;    // APB2 clock
};

namespace detail {

using namespace sbl::hw::reg;

// ============================================================================
// Manual supplements — field values not generated by cecrops
// cecrops generates Pos/Msk for each field but not enumerated values.
// ============================================================================

// RCC_CFGR.SW field values (RM0433 §8.7.7)
constexpr uint32_t CFGR_SW_PLL1 = 3u;                                         // Select PLL1 as SYSCLK
constexpr uint32_t CFGR_SWS_PLL1 = (3u << RCC::CFGR_SWS_Pos);                // PLL1 selected status

// RCC_PLLCKSELR.PLLSRC field value (RM0433 §8.7.10)
constexpr uint32_t PLLCKSELR_PLLSRC_HSE = (2u << RCC::PLLCKSELR_PLLSRC_Pos); // HSE as PLL source

// RCC_PLLCFGR.PLL1RGE / PLL3RGE field value (RM0433 §8.7.11)
constexpr uint32_t PLLCFGR_PLL1RGE_4_8 = (2u << RCC::PLLCFGR_PLL1RGE_Pos);   // Input 4-8 MHz
constexpr uint32_t PLLCFGR_PLL3RGE_4_8 = (2u << RCC::PLLCFGR_PLL3RGE_Pos);   // Input 4-8 MHz

// RCC_D2CCIP2R.USBSEL field value (RM0433 §8.7.15)
constexpr uint32_t D2CCIP2R_USBSEL_PLL3Q = (2u << RCC::D2CCIP2R_USBSEL_Pos); // PLL3Q for USB

// PWR_D3CR.VOS field value (RM0433 §5.8.6)
constexpr uint32_t D3CR_VOS_SCALE1 = (3u << PWR::PWR_D3CR_VOS_Pos);           // VOS1 for 480 MHz

// SYSCFG registers — not in cecrops outputs (RM0433 §5.8.4)
constexpr uint32_t SYSCFG_BASE = 0x58000400UL;
constexpr uint32_t SYSCFG_PWRCR_OFFSET = 0x04;
constexpr uint32_t SYSCFG_PWRCR_ODEN = (1u << 0);  // Overdrive enable for VOS0

/**
 * @brief Configure power supply and voltage scaling for 480 MHz (VOS0)
 *
 * STM32H750 at 480 MHz requires VOS0 (overdrive mode). The sequence is:
 * 1. Set VOS1 in PWR_D3CR
 * 2. Wait for VOSRDY
 * 3. Enable SYSCFG clock
 * 4. Set ODEN bit in SYSCFG_PWRCR
 * 5. Wait for ACTVOSRDY in PWR_CSR1
 *
 * VOS1 only supports up to 400 MHz - this was the bug!
 */
inline void configure_power() {
    using namespace sbl::hw::reg;

    // Enable LDO power supply (default for STM32H750)
    periph::pwr->PWR_CR3 |= PWR::PWR_CR3_LDOEN;
    periph::pwr->PWR_CR3 &= ~PWR::PWR_CR3_SDEN;  // Disable SMPS

    // Step 1: Set voltage scaling to VOS1 (prerequisite for VOS0)
    uint32_t d3cr = periph::pwr->PWR_D3CR;
    d3cr &= ~PWR::PWR_D3CR_VOS_Msk;
    d3cr |= D3CR_VOS_SCALE1;  // VOS1 = bits 15:14 = 11
    periph::pwr->PWR_D3CR = d3cr;

    // Step 2: Wait for VOS1 ready
    wait_for(&periph::pwr->PWR_D3CR, PWR::PWR_D3CR_VOSRDY, PWR::PWR_D3CR_VOSRDY);

    // Step 3: Enable SYSCFG clock (needed to access SYSCFG_PWRCR)
    periph::rcc->APB4ENR |= RCC::APB4ENR_SYSCFGEN;
    volatile uint32_t dummy = periph::rcc->APB4ENR;  // Read-back for clock sync
    (void)dummy;

    // Step 4: Enable overdrive (VOS0) via SYSCFG_PWRCR.ODEN
    volatile uint32_t& SYSCFG_PWRCR = *reinterpret_cast<volatile uint32_t*>(SYSCFG_BASE + SYSCFG_PWRCR_OFFSET);
    SYSCFG_PWRCR |= SYSCFG_PWRCR_ODEN;

    // Step 5: Wait for VOS0 active (ACTVOSRDY in PWR_CSR1)
    wait_for(&periph::pwr->PWR_CSR1, PWR::PWR_CSR1_ACTVOSRDY, PWR::PWR_CSR1_ACTVOSRDY);
}

/**
 * @brief Configure flash latency for target frequency
 */
inline void configure_flash(uint32_t sysclk_mhz) {
    using namespace sbl::hw::reg;

    // Flash latency depends on frequency and voltage scale
    // At VOS0 (overdrive): 4 wait states for 450-480 MHz
    uint32_t latency;
    if (sysclk_mhz <= 70) {
        latency = 0;
    } else if (sysclk_mhz <= 140) {
        latency = 1;
    } else if (sysclk_mhz <= 210) {
        latency = 2;
    } else if (sysclk_mhz <= 275) {
        latency = 3;
    } else {
        latency = 4;  // 280-480 MHz
    }

    // Also set WRHIGHFREQ for programming at high frequencies
    uint32_t wrhighfreq = (sysclk_mhz > 185) ? 2 : ((sysclk_mhz > 70) ? 1 : 0);

    uint32_t acr = periph::flash->ACR;
    acr &= ~(Flash::ACR_LATENCY_Msk | Flash::ACR_WRHIGHFREQ_Msk);
    acr |= latency | (wrhighfreq << Flash::ACR_WRHIGHFREQ_Pos);
    periph::flash->ACR = acr;

    // Wait for latency to be applied
    wait_for(&periph::flash->ACR, Flash::ACR_LATENCY_Msk, latency);
}

/**
 * @brief Enable HSE and wait for ready
 */
inline bool enable_hse() {
    using namespace sbl::hw::reg;

    periph::rcc->CR |= RCC::CR_HSEON;

    // Wait for HSE ready (with timeout)
    // At 64 MHz, 500k iterations ≈ 50ms - plenty for crystal startup
    for (uint32_t i = 0; i < 500'000; ++i) {
        if (periph::rcc->CR & RCC::CR_HSERDY) {
            return true;
        }
    }
    return false;  // HSE failed to start
}

/**
 * @brief Configure PLL3 to provide 48 MHz USB clock
 *
 * PLL3 config: 16 MHz HSE -> 4 MHz input -> 192 MHz VCO -> 48 MHz Q output
 * This must be called AFTER HSE is enabled.
 *
 * @param hse_mhz HSE frequency in MHz (typically 16 for Daisy Seed)
 * @return true if PLL3 locked successfully
 */
inline bool configure_pll3_usb(uint32_t hse_mhz) {
    using namespace sbl::hw::reg;

    // Disable PLL3 before configuring
    periph::rcc->CR &= ~RCC::CR_PLL3ON;
    while (periph::rcc->CR & RCC::CR_PLL3RDY) {}

    // Small delay after disabling PLL to ensure register writes are accepted
    for (volatile int i = 0; i < 100; ++i) { __asm__ volatile("nop"); }

    // Configure PLL3 dividers in PLLCKSELR
    // DIVM3 = HSE/4 = 4 MHz PLL input (same as PLL1)
    uint32_t divm3 = hse_mhz / 4;
    uint32_t pllckselr = periph::rcc->PLLCKSELR;
    pllckselr &= ~(0x3Fu << 20);  // Clear DIVM3 field
    pllckselr |= (divm3 << 20);   // Set DIVM3
    periph::rcc->PLLCKSELR = pllckselr;

    // Configure PLL3 in PLLCFGR
    // PLL3RGE = 4-8 MHz input range, enable Q output
    // IMPORTANT: Read-modify-write to preserve PLL1 settings
    uint32_t pllcfgr = periph::rcc->PLLCFGR;
    pllcfgr &= ~RCC::PLLCFGR_PLL3RGE_Msk;          // Clear PLL3RGE
    pllcfgr |= PLLCFGR_PLL3RGE_4_8;                 // Set 4-8 MHz range
    pllcfgr |= RCC::PLLCFGR_DIVQ3EN;                // Enable Q output
    periph::rcc->PLLCFGR = pllcfgr;

    // Memory barrier to ensure write completes before continuing
    __asm__ volatile("dsb" ::: "memory");
    __asm__ volatile("isb");

    // Verify DIVQ3EN was actually set (debugging: some STM32H7 have errata)
    if ((periph::rcc->PLLCFGR & RCC::PLLCFGR_DIVQ3EN) == 0) {
        // Try direct write if read-modify-write failed
        periph::rcc->PLLCFGR |= RCC::PLLCFGR_DIVQ3EN;
        __asm__ volatile("dsb" ::: "memory");
    }

    // Configure PLL3 dividers for 48 MHz output
    // VCO = 4 MHz * 48 = 192 MHz, Q = VCO / 4 = 48 MHz
    // DIVN3 = 48 (N multiplier), DIVQ3 = 4 (Q divider)
    uint32_t divn3 = 48;
    uint32_t divq3 = 4;
    periph::rcc->PLL3DIVR = ((divn3 - 1) << 0) | ((divq3 - 1) << 16);

    // Enable PLL3 and wait for lock
    periph::rcc->CR |= RCC::CR_PLL3ON;
    for (uint32_t i = 0; i < 500000; ++i) {
        if (periph::rcc->CR & RCC::CR_PLL3RDY) {
            return true;
        }
    }
    return false;  // PLL3 failed to lock
}

/**
 * @brief Select PLL3Q as USB clock source
 */
inline void select_usb_clock_pll3() {
    using namespace sbl::hw::reg;

    uint32_t d2ccip2r = periph::rcc->D2CCIP2R;
    d2ccip2r &= ~RCC::D2CCIP2R_USBSEL_Msk;
    d2ccip2r |= D2CCIP2R_USBSEL_PLL3Q;
    periph::rcc->D2CCIP2R = d2ccip2r;
}


// RCC_D2CCIP1R.SAI1SEL field value (RM0433 §8.7.14)
constexpr uint32_t D2CCIP1R_SAI1SEL_PLL2P = (1u << RCC::D2CCIP1R_SAI1SEL_Pos); // PLL2P for SAI1

// RCC_PLLCFGR.PLL2RGE field value (RM0433 §8.7.11)
constexpr uint32_t PLLCFGR_PLL2RGE_4_8 = (2u << RCC::PLLCFGR_PLL2RGE_Pos);   // Input 4-8 MHz

// PLL2 fractional config: HSE/4 × (196 + 4981/8192) / 64 = 12.288 MHz
// Produces 48 kHz × 256 MCLK with <1 ppm error
constexpr uint32_t PLL2_DIVM  = 4;     // HSE prescaler → 4 MHz PLL input
constexpr uint32_t PLL2_DIVN  = 196;   // VCO integer multiplier
constexpr uint32_t PLL2_FRACN = 4981;  // Fractional numerator (/8192)
constexpr uint32_t PLL2_DIVP  = 64;    // P output divider → 12.288 MHz

/**
 * @brief Configure PLL2 fractional mode for audio clocks
 *
 * PLL2 produces 12.288 MHz for 48 kHz audio (256×Fs MCLK).
 *
 * Config: 16 MHz HSE → /4 → 4 MHz → ×196.608 (fractional) → 786.432 MHz VCO → /64 → 12.288 MHz
 *   DIVN2 = 196 (integer), FRACN2 = 4981 → N_eff = 196 + 4981/8192 = 196.6078
 *   VCO = 4 × 196.6078 = 786.431 MHz, PLL2P = 786.431/64 = 12.288 MHz (<1 ppm error)
 *
 * Must be called AFTER init() (HSE must be running).
 */
inline bool configure_pll2_audio(uint32_t hse_mhz = 16) {
    using namespace sbl::hw::reg;

    // Disable PLL2 before configuring
    periph::rcc->CR &= ~RCC::CR_PLL2ON;
    while (periph::rcc->CR & RCC::CR_PLL2RDY) {}

    // Small delay after disabling PLL
    for (volatile int i = 0; i < 100; ++i) { __asm__ volatile("nop"); }

    // Configure PLL2 prescaler in PLLCKSELR (shared register — preserve PLL1/3)
    uint32_t divm2 = hse_mhz / PLL2_DIVM;
    uint32_t pllckselr = periph::rcc->PLLCKSELR;
    pllckselr &= ~RCC::PLLCKSELR_DIVM2_Msk;
    pllckselr |= (divm2 << RCC::PLLCKSELR_DIVM2_Pos);
    periph::rcc->PLLCKSELR = pllckselr;

    // Configure PLL2 in PLLCFGR (shared register — preserve PLL1/3)
    // PLL2RGE = 4-8 MHz, PLL2VCOSEL = 0 (wide VCO 192-836 MHz), FRACEN, DIVP2EN
    uint32_t pllcfgr = periph::rcc->PLLCFGR;
    pllcfgr &= ~(RCC::PLLCFGR_PLL2RGE_Msk | RCC::PLLCFGR_PLL2VCOSEL_Msk);
    pllcfgr |= PLLCFGR_PLL2RGE_4_8;        // 4-8 MHz input range
    pllcfgr |= RCC::PLLCFGR_PLL2FRACEN;     // Enable fractional mode
    pllcfgr |= RCC::PLLCFGR_DIVP2EN;        // Enable P output
    periph::rcc->PLLCFGR = pllcfgr;

    __asm__ volatile("dsb" ::: "memory");
    __asm__ volatile("isb");

    // Set integer dividers: DIVN2=196-1, DIVP2=64-1
    periph::rcc->PLL2DIVR = ((PLL2_DIVN - 1) << RCC::PLL2DIVR_DIVN2_Pos)
                           | ((PLL2_DIVP - 1) << RCC::PLL2DIVR_DIVP2_Pos);

    // Set fractional part → 12.288 MHz output
    periph::rcc->PLL2FRACR = (PLL2_FRACN << RCC::PLL2FRACR_FRACN2_Pos);

    // Enable PLL2 and wait for lock
    periph::rcc->CR |= RCC::CR_PLL2ON;
    for (uint32_t i = 0; i < 500'000; ++i) {
        if (periph::rcc->CR & RCC::CR_PLL2RDY) {
            return true;
        }
    }
    return false;  // PLL2 failed to lock
}

/**
 * @brief Select PLL2P as SAI1 clock source
 */
inline void select_sai1_clock_pll2p() {
    using namespace sbl::hw::reg;

    uint32_t d2ccip1r = periph::rcc->D2CCIP1R;
    d2ccip1r &= ~RCC::D2CCIP1R_SAI1SEL_Msk;
    d2ccip1r |= D2CCIP1R_SAI1SEL_PLL2P;
    periph::rcc->D2CCIP1R = d2ccip1r;
}

/**
 * @brief Configure SAI1 GPIO pins (PE2-PE6) as AF6
 *
 * Daisy Seed SAI1 connections:
 *   PE2 = MCLK (AF6), PE3 = SD_B/RX (AF6), PE4 = FS (AF6)
 *   PE5 = SCK (AF6),  PE6 = SD_A/TX (AF6)
 */
inline void configure_sai_gpio() {
    using namespace sbl::hw::reg;

    // Enable GPIOE clock
    periph::rcc->AHB4ENR |= RCC::AHB4ENR_GPIOEEN;
    volatile uint32_t dummy = periph::rcc->AHB4ENR;
    (void)dummy;

    // Configure PE2, PE3, PE4, PE5, PE6 as alternate function mode (10b)
    uint32_t moder = periph::gpioe->GPIO_MODER;
    for (uint8_t pin = 2; pin <= 6; ++pin) {
        moder &= ~(3u << (pin * 2));
        moder |= (2u << (pin * 2));     // AF mode
    }
    periph::gpioe->GPIO_MODER = moder;

    // Very high speed for all SAI pins
    uint32_t ospeedr = periph::gpioe->GPIO_OSPEEDR;
    for (uint8_t pin = 2; pin <= 6; ++pin) {
        ospeedr |= (3u << (pin * 2));
    }
    periph::gpioe->GPIO_OSPEEDR = ospeedr;

    // No pull-up/pull-down
    uint32_t pupdr = periph::gpioe->GPIO_PUPDR;
    for (uint8_t pin = 2; pin <= 6; ++pin) {
        pupdr &= ~(3u << (pin * 2));
    }
    periph::gpioe->GPIO_PUPDR = pupdr;

    // Set alternate function 6 for PE2-PE6 (all in AFRL — pins 0-7)
    uint32_t afrl = periph::gpioe->GPIO_AFRL;
    for (uint8_t pin = 2; pin <= 6; ++pin) {
        afrl &= ~(0xFu << (pin * 4));
        afrl |= (6u << (pin * 4));      // AF6 = SAI1
    }
    periph::gpioe->GPIO_AFRL = afrl;
}

/**
 * @brief Assert AK4556 codec reset (PB11 high)
 *
 * The AK4556 is hardware-configured — just hold reset high and it runs
 * in its default I2S mode.
 */
inline void codec_reset_release() {
    using namespace sbl::hw::reg;

    // Enable GPIOB clock
    periph::rcc->AHB4ENR |= RCC::AHB4ENR_GPIOBEN;
    volatile uint32_t dummy = periph::rcc->AHB4ENR;
    (void)dummy;

    // PB11 as general-purpose output (01b)
    uint32_t moder = periph::gpiob->GPIO_MODER;
    moder &= ~(3u << (11 * 2));
    moder |= (1u << (11 * 2));
    periph::gpiob->GPIO_MODER = moder;

    // Drive PB11 low first (hold codec in reset)
    periph::gpiob->GPIO_BSRR = (1u << (11 + 16));  // Reset (low)

    // Brief reset pulse (~1ms)
    for (volatile uint32_t i = 0; i < 100'000; ++i) {
        __asm__ volatile("nop");
    }

    // Release reset (high)
    periph::gpiob->GPIO_BSRR = (1u << 11);  // Set (high)

    // Give codec time to initialize (~1ms)
    for (volatile uint32_t i = 0; i < 100'000; ++i) {
        __asm__ volatile("nop");
    }
}

/**
 * @brief Enable USB2 OTG FS peripheral clock
 */
inline void enable_usb2_clock() {
    using namespace sbl::hw::reg;
    periph::rcc->AHB1ENR |= RCC::AHB1ENR_USB2OTGHSEN;  // SVD name: "HS" for both controllers
    // Longer delay for USB clock to stabilize before core can be accessed
    for (volatile int i = 0; i < 100000; ++i) {
        __asm__ volatile("nop");
    }
}

/**
 * @brief Configure PA11/PA12 as USB DM/DP pins
 *
 * Configures:
 * - PA11 as USB2 DM (alternate function 10)
 * - PA12 as USB2 DP (alternate function 10)
 * - Push-pull, no pull, very high speed
 */
inline void configure_usb_gpio() {
    using namespace sbl::hw::reg;

    // Enable GPIOA clock
    periph::rcc->AHB4ENR |= RCC::AHB4ENR_GPIOAEN;
    volatile uint32_t dummy = periph::rcc->AHB4ENR;
    (void)dummy;

    // PA11 and PA12 configuration
    // MODER: Alternate function (10b)
    // OSPEEDR: Very high speed (11b)
    // PUPDR: No pull (00b)
    // AFRH: AF10 for PA11 and PA12

    // Set PA11, PA12 to alternate function mode
    uint32_t moder = periph::gpioa->GPIO_MODER;
    moder &= ~((3u << (11 * 2)) | (3u << (12 * 2)));  // Clear bits
    moder |= (2u << (11 * 2)) | (2u << (12 * 2));     // Set to AF mode
    periph::gpioa->GPIO_MODER = moder;

    // Set to very high speed
    uint32_t ospeedr = periph::gpioa->GPIO_OSPEEDR;
    ospeedr |= (3u << (11 * 2)) | (3u << (12 * 2));
    periph::gpioa->GPIO_OSPEEDR = ospeedr;

    // No pull-up/pull-down
    uint32_t pupdr = periph::gpioa->GPIO_PUPDR;
    pupdr &= ~((3u << (11 * 2)) | (3u << (12 * 2)));
    periph::gpioa->GPIO_PUPDR = pupdr;

    // Set alternate function to AF10 (USB2 OTG FS)
    // PA11 is in AFRH (pins 8-15), bit positions [15:12]
    // PA12 is in AFRH (pins 8-15), bit positions [19:16]
    uint32_t afrh = periph::gpioa->GPIO_AFRH;
    afrh &= ~((0xFu << ((11 - 8) * 4)) | (0xFu << ((12 - 8) * 4)));
    afrh |= (10u << ((11 - 8) * 4)) | (10u << ((12 - 8) * 4));  // AF10
    periph::gpioa->GPIO_AFRH = afrh;
}

} // namespace detail

/**
 * @brief Initialize STM32H750 for 480 MHz operation
 *
 * Configures:
 * - Power supply (LDO, VOS1)
 * - Flash latency
 * - HSE oscillator
 * - PLL1 for 480 MHz
 * - Bus clocks (AHB, APB)
 * - SysTick timer
 *
 * @note Not ISR-safe — blocking. Boot-time only.
 *
 * @param config Clock configuration (defaults to 480 MHz from 16 MHz HSE)
 * @return true if initialization successful
 */
inline bool init(const ClockConfig& config = ClockConfig{}) {
    using namespace detail;
    using namespace sbl::hw::reg;

    // Init timer on HSI first (allows delays during clock setup if needed)
    Timer::init(64'000'000);

    // Power and flash config for target frequency
    configure_power();
    configure_flash(config.sysclk_mhz);

    // Try to start HSE
    if (!enable_hse()) {
        // HSE failed - stay on HSI
        return false;
    }

    // --- PLL1 Configuration ---
    // 16 MHz HSE -> 4 MHz PLL input -> 960 MHz VCO -> 480 MHz SYSCLK

    // Disable PLL1 before configuring
    periph::rcc->CR &= ~RCC::CR_PLL1ON;
    while (periph::rcc->CR & RCC::CR_PLL1RDY) {}

    // PLL source = HSE, DIVM1 = 4 (16MHz / 4 = 4MHz PLL input)
    uint32_t divm1 = config.hse_mhz / 4;
    periph::rcc->PLLCKSELR = PLLCKSELR_PLLSRC_HSE | (divm1 << 4);

    // PLL1 config: input range 4-8MHz (PLL1RGE=2), enable P and Q outputs
    // P = SYSCLK (480 MHz), Q = SDMMC/general (48 MHz)
    periph::rcc->PLLCFGR = PLLCFGR_PLL1RGE_4_8
                          | RCC::PLLCFGR_DIVP1EN
                          | RCC::PLLCFGR_DIVQ1EN;

    // Calculate dividers for target frequency
    // VCO = target * 2 = 960 MHz, DIVN = VCO / PLL_input = 960 / 4 = 240
    // DIVP = 2 → 480 MHz SYSCLK, DIVQ = 20 → 48 MHz (SDMMC, etc.)
    uint32_t pll_input_mhz = config.hse_mhz / divm1;
    uint32_t vco_mhz = config.sysclk_mhz * 2;
    uint32_t divn = vco_mhz / pll_input_mhz;
    uint32_t divp = 2;
    uint32_t divq = vco_mhz / 48;  // 960/48 = 20
    periph::rcc->PLL1DIVR = ((divn - 1) << RCC::PLL1DIVR_DIVN1_Pos)
                           | ((divp - 1) << RCC::PLL1DIVR_DIVP1_Pos)
                           | ((divq - 1) << RCC::PLL1DIVR_DIVQ1_Pos);

    // Enable PLL1 and wait for lock
    periph::rcc->CR |= RCC::CR_PLL1ON;
    for (uint32_t i = 0; i < 500000; ++i) {
        if (periph::rcc->CR & RCC::CR_PLL1RDY) {
            // PLL locked - configure bus dividers and switch

            // D1: CPU=SYSCLK, AHB=SYSCLK/2 (240 MHz)
            periph::rcc->D1CFGR = (0 << 8) | (8 << 0);
            // D2: APB1=APB2=AHB/2 (120 MHz)
            periph::rcc->D2CFGR = (4 << 4) | (4 << 8);
            // D3: APB4=AHB/2 (120 MHz)
            periph::rcc->D3CFGR = (4 << 4);

            // Switch to PLL1
            periph::rcc->CFGR = (periph::rcc->CFGR & ~RCC::CFGR_SW_Msk) | CFGR_SW_PLL1;
            while ((periph::rcc->CFGR & RCC::CFGR_SWS_Msk) != CFGR_SWS_PLL1) {}

            // Update SystemCoreClock for CMSIS-compatible code (e.g., TinyUSB)
            SystemCoreClock = config.sysclk_mhz * 1'000'000;

            // Reinit timer for actual frequency
            Timer::init(config.sysclk_mhz * 1'000'000);
            return true;
        }
    }

    // PLL failed to lock - stay on HSI
    return false;
}

/**
 * @brief Quick initialization using HSI (no HSE required)
 *
 * Runs at 64 MHz internal oscillator - useful for debugging
 * or when HSE is not available.
 *
 * @note Not ISR-safe — boot-time only.
 */
inline void init_hsi() {
    // Default HSI is already running at 64 MHz
    // Just initialize the timer
    Timer::init(64'000'000);
}

/**
 * @brief Enable USB 3.3V internal power supply
 *
 * STM32H7 has an internal 3.3V supply for the USB transceiver.
 * This MUST be enabled before USB can work.
 */
inline void enable_usb_power() {
    using namespace sbl::hw::reg;

    // Enable internal 3.3V supply for USB transceiver
    periph::pwr->PWR_CR3 |= PWR::PWR_CR3_USB33DEN;

    // Wait for USB 3.3V regulator ready
    // Should stabilize in a few microseconds, use generous timeout
    for (volatile uint32_t i = 0; i < 100000; ++i) {
        if (periph::pwr->PWR_CR3 & PWR::PWR_CR3_USB33RDY) {
            return;  // Regulator ready
        }
    }
    // Continue anyway - may work without explicit ready bit
}

/**
 * @brief Configure USB2 OTG FS peripheral for device mode
 *
 * Configures the DWC2 USB controller for device mode without VBUS sensing.
 * This is required for boards like Daisy Seed where VBUS isn't connected
 * to the USB peripheral.
 */
inline void configure_usb2_device_mode() {
    using namespace sbl::hw::reg;

    auto* usb = periph::usb2_global;

    // Disable VBUS sensing
    usb->GCCFG &= ~GCCFG::VBDEN;

    // Enable internal FS PHY (PWRDWN is active-high: 1 = PHY enabled)
    usb->GCCFG |= GCCFG::PWRDWN;

    // Force B-session valid (bypass VBUS detection for boards without VBUS sensing)
    usb->GOTGCTL |= GOTGCTL::BVALOEN | GOTGCTL::BVALOVAL;

    // Force device mode
    usb->GUSBCFG |= GUSBCFG::FDMOD;

    // Wait for mode change to take effect
    for (volatile int i = 0; i < 100000; ++i) {
        __asm__ volatile("nop");
    }
}

/**
 * @brief Enable USB2 OTG FS interrupt in NVIC
 *
 * USB2_OTG_FS is IRQ 101 (see reg/irq.hpp)
 */
inline void enable_usb2_nvic() {
    using namespace sbl::hw::reg;

    constexpr auto irq = IRQn::OTG_FS;
    constexpr uint32_t n = static_cast<uint32_t>(irq);

    // Enable interrupt: ISER[n/32] bit n%32
    periph::nvic->ISER[n >> 5] = (1u << (n & 0x1Fu));

    // Set priority (lower number = higher priority, shifted to upper nibble)
    periph::nvic->IP[n] = (4u << 4);  // Priority 4
}

/**
 * @brief Enable USB1 OTG HS peripheral clock and select FS PHY
 *
 * USB1_OTG_HS defaults to ULPI PHY mode (PHYSEL=0) at reset.
 * When using the internal FS PHY (no external ULPI connected),
 * PHYSEL MUST be set to 1 immediately after enabling the AHB clock.
 * Otherwise the DWC2 core starts up expecting a ULPI clock that
 * doesn't exist, preventing AHB idle (GRSTCTL.AHBIDL) and causing
 * TinyUSB's core reset to hang.
 *
 * This is not needed for USB2_OTG_FS which defaults to PHYSEL=1.
 * See RM0433 §57.12.3 and RPT-004/005 for background.
 */
inline void enable_usb1_clock() {
    using namespace sbl::hw::reg;

    // Enable USB1 AHB clock
    periph::rcc->AHB1ENR |= RCC::AHB1ENR_USB1OTGHSEN;

    // Disable ULPI clock (using internal FS PHY, not external ULPI)
    periph::rcc->AHB1ENR &= ~RCC::AHB1ENR_USB1OTGHSULPIEN;

    // Brief delay for AHB clock to reach the USB1 controller
    for (volatile int i = 0; i < 1000; ++i) {
        __asm__ volatile("nop");
    }

    // Select internal FS PHY IMMEDIATELY — before the DWC2 core tries
    // to use the non-existent ULPI PHY. This is the critical difference
    // vs USB2_OTG_FS which defaults to FS PHY (PHYSEL=1 at reset).
    periph::usb1_global->GUSBCFG |= GUSBCFG::PHYSEL;

    // Enable FS PHY power (PWRDWN is active-high: 1 = PHY enabled)
    periph::usb1_global->GCCFG |= GCCFG::PWRDWN;

    // Wait for PHY clock to stabilize after switching from ULPI to FS
    for (volatile int i = 0; i < 100000; ++i) {
        __asm__ volatile("nop");
    }
}

/**
 * @brief Configure PB14/PB15 as USB DM/DP pins (USB1 OTG HS in FS mode)
 *
 * Configures:
 * - PB14 as USB1 DM (alternate function 12)
 * - PB15 as USB1 DP (alternate function 12)
 * - Push-pull, no pull, very high speed
 */
inline void configure_usb_gpio_hs() {
    using namespace sbl::hw::reg;

    // Enable GPIOB clock
    periph::rcc->AHB4ENR |= RCC::AHB4ENR_GPIOBEN;
    volatile uint32_t dummy = periph::rcc->AHB4ENR;
    (void)dummy;

    // Set PB14, PB15 to alternate function mode (10b)
    uint32_t moder = periph::gpiob->GPIO_MODER;
    moder &= ~((3u << (14 * 2)) | (3u << (15 * 2)));
    moder |= (2u << (14 * 2)) | (2u << (15 * 2));
    periph::gpiob->GPIO_MODER = moder;

    // Low speed (00b) — matches libDaisy; FS USB doesn't need high slew rate
    uint32_t ospeedr = periph::gpiob->GPIO_OSPEEDR;
    ospeedr &= ~((3u << (14 * 2)) | (3u << (15 * 2)));
    periph::gpiob->GPIO_OSPEEDR = ospeedr;

    // No pull-up/pull-down
    uint32_t pupdr = periph::gpiob->GPIO_PUPDR;
    pupdr &= ~((3u << (14 * 2)) | (3u << (15 * 2)));
    periph::gpiob->GPIO_PUPDR = pupdr;

    // AF12 for PB14 and PB15 (USB OTG HS)
    // PB14 is in AFRH bit positions [27:24], PB15 is [31:28]
    uint32_t afrh = periph::gpiob->GPIO_AFRH;
    afrh &= ~((0xFu << ((14 - 8) * 4)) | (0xFu << ((15 - 8) * 4)));
    afrh |= (12u << ((14 - 8) * 4)) | (12u << ((15 - 8) * 4));
    periph::gpiob->GPIO_AFRH = afrh;
}

/**
 * @brief Enable USB1 OTG HS main interrupt in NVIC
 *
 * Only enable the main OTG_HS IRQ (77). The DWC2 controller routes all
 * events through this single interrupt. The separate EP1_OUT (74) and
 * EP1_IN (75) IRQs are ST HAL specific and not used by TinyUSB.
 */
inline void enable_usb1_nvic() {
    using namespace sbl::hw::reg;

    constexpr auto irq = IRQn::OTG_HS;
    constexpr uint32_t n = static_cast<uint32_t>(irq);

    periph::nvic->ISER[n >> 5] = (1u << (n & 0x1Fu));
    periph::nvic->IP[n] = (4u << 4);  // Priority 4
}

/**
 * @brief Initialize USB clocks and peripheral
 *
 * Selects USB1_OTG_HS (PB14/PB15) or USB2_OTG_FS (PA11/PA12) based on
 * the SBL_USB_OTG_HS compile define.
 *
 * Must be called AFTER init() to ensure HSE is running.
 *
 * @param hse_mhz HSE frequency (default 16 MHz)
 * @return true if USB clock setup successful
 */
inline bool init_usb(uint32_t hse_mhz = 16) {
    using namespace detail;

    // Enable USB 3.3V internal power supply (MUST be first!)
    enable_usb_power();

    // Configure PLL3 for 48 MHz USB clock
    if (!configure_pll3_usb(hse_mhz)) {
        return false;
    }

    // Select PLL3Q as USB clock source
    select_usb_clock_pll3();

#ifdef SBL_USB_OTG_HS
    // Patch SM: USB1_OTG_HS on PB14/PB15 (FS mode with internal PHY)
    configure_usb_gpio_hs();
    enable_usb1_clock();
    enable_usb1_nvic();
#else
    // Daisy Seed: USB2_OTG_FS on PA11/PA12
    configure_usb_gpio();
    enable_usb2_clock();
    enable_usb2_nvic();
#endif

    return true;
}

/**
 * @brief Initialize audio subsystem (PLL2, SAI GPIO, codec reset)
 *
 * Configures:
 * - PLL2 fractional mode for 12.288 MHz audio MCLK (48 kHz × 256)
 * - SAI1 clock source = PLL2P
 * - SAI1 GPIO pins (PE2-PE6, AF6)
 * - SAI1 peripheral clock
 * - AK4556 codec reset release (PB11)
 *
 * Must be called AFTER init() to ensure HSE is running.
 *
 * @note Not ISR-safe — blocking. Boot-time only.
 *
 * @param hse_mhz HSE frequency (default 16 MHz for Daisy Seed)
 * @return true if audio clock setup successful
 */
inline bool init_audio(uint32_t hse_mhz = 16) {
    using namespace detail;
    using namespace sbl::hw::reg;

    // Configure PLL2 for audio clock
    if (!configure_pll2_audio(hse_mhz)) {
        return false;
    }

    // Select PLL2P as SAI1 clock source
    select_sai1_clock_pll2p();

    // Configure SAI1 GPIO (PE2-PE6 as AF6)
    configure_sai_gpio();

    // Enable SAI1 peripheral clock
    periph::rcc->APB2ENR |= RCC::APB2ENR_SAI1EN;
    volatile uint32_t dummy = periph::rcc->APB2ENR;
    (void)dummy;

    // Release codec from reset (PB11 high)
    codec_reset_release();

    return true;
}

/**
 * @brief Initialize SDMMC1 clocks and GPIO
 *
 * Configures:
 * - D1CCIPR.SDMMCSEL = PLL1Q (48 MHz, configured in init())
 * - AHB3 bus clock for SDMMC1
 * - GPIO: PC8(D0), PC9(D1), PC10(D2), PC11(D3), PC12(CK), PD2(CMD) as AF12
 *
 * NOTE: PC10/PC11 conflict with USART3 — cannot use debug UART and SD card
 * simultaneously on Daisy Pod.
 *
 * Must be called AFTER init() (PLL1Q must be running).
 *
 * @note Not ISR-safe — blocking. Boot-time only.
 */
inline void init_sdmmc() {
    using namespace detail;
    using namespace sbl::hw::reg;

    // Select PLL1Q as SDMMC kernel clock (D1CCIPR.SDMMCSEL = 0)
    uint32_t d1ccipr = periph::rcc->D1CCIPR;
    d1ccipr &= ~RCC::D1CCIPR_SDMMCSEL;  // Bit 16 = 0 → PLL1Q
    periph::rcc->D1CCIPR = d1ccipr;

    // Enable SDMMC1 bus clock on AHB3
    periph::rcc->AHB3ENR |= RCC::AHB3ENR_SDMMC1EN;
    volatile uint32_t dummy = periph::rcc->AHB3ENR;
    (void)dummy;

    // Enable GPIOC and GPIOD clocks
    periph::rcc->AHB4ENR |= RCC::AHB4ENR_GPIOCEN | RCC::AHB4ENR_GPIODEN;
    dummy = periph::rcc->AHB4ENR;
    (void)dummy;

    // Configure GPIOC pins 8-12 as AF12 (SDMMC1), very high speed, push-pull, pull-up
    // PC8=D0, PC9=D1, PC10=D2, PC11=D3, PC12=CK
    uint32_t moder = periph::gpioc->GPIO_MODER;
    uint32_t ospeedr = periph::gpioc->GPIO_OSPEEDR;
    uint32_t pupdr = periph::gpioc->GPIO_PUPDR;
    uint32_t afrh = periph::gpioc->GPIO_AFRH;

    for (uint8_t pin = 8; pin <= 12; ++pin) {
        moder &= ~(3u << (pin * 2));
        moder |= (2u << (pin * 2));      // AF mode
        ospeedr |= (3u << (pin * 2));     // Very high speed
        pupdr &= ~(3u << (pin * 2));
        pupdr |= (1u << (pin * 2));       // Pull-up (data lines + CK)
        afrh &= ~(0xFu << ((pin - 8) * 4));
        afrh |= (12u << ((pin - 8) * 4)); // AF12 = SDMMC1
    }

    periph::gpioc->GPIO_MODER = moder;
    periph::gpioc->GPIO_OSPEEDR = ospeedr;
    periph::gpioc->GPIO_PUPDR = pupdr;
    periph::gpioc->GPIO_AFRH = afrh;

    // Configure PD2 as AF12 (SDMMC1_CMD), very high speed, pull-up
    moder = periph::gpiod->GPIO_MODER;
    moder &= ~(3u << (2 * 2));
    moder |= (2u << (2 * 2));            // AF mode
    periph::gpiod->GPIO_MODER = moder;

    ospeedr = periph::gpiod->GPIO_OSPEEDR;
    ospeedr |= (3u << (2 * 2));           // Very high speed
    periph::gpiod->GPIO_OSPEEDR = ospeedr;

    pupdr = periph::gpiod->GPIO_PUPDR;
    pupdr &= ~(3u << (2 * 2));
    pupdr |= (1u << (2 * 2));             // Pull-up
    periph::gpiod->GPIO_PUPDR = pupdr;

    uint32_t afrl = periph::gpiod->GPIO_AFRL;
    afrl &= ~(0xFu << (2 * 4));
    afrl |= (12u << (2 * 4));             // AF12 = SDMMC1
    periph::gpiod->GPIO_AFRL = afrl;
}

} // namespace sbl::driver

#endif // SBL_HW_DRIVER_INIT_HPP_
