/**
 * @file soft_pwm.hpp
 * @brief Software PWM via Binary Coded Modulation (BCM) on TIM7
 *
 * BCM outputs each bit of the duty cycle for a proportional duration:
 * bit 0 for T, bit 1 for 2T, ..., bit 7 for 128T. Total cycle = 255T.
 * At T = 4 us -> ~980 Hz refresh with only 8 ISR calls per cycle.
 *
 * Each ISR: clear flag, write one BSRR per used GPIO port, reload ARR.
 * Under 50 cycles at 480 MHz — negligible CPU overhead (~0.08%).
 *
 * Usage:
 *   uint8_t ch = sbl::driver::SoftPwm::add_channel(gpio_handle);
 *   sbl::driver::SoftPwm::start();
 *   // ...
 *   sbl::driver::SoftPwm::set_duty(ch, 128);  // 50% duty
 */
#ifndef SBL_HW_DRIVER_SOFT_PWM_HPP_
#define SBL_HW_DRIVER_SOFT_PWM_HPP_

#include <cstdint>
#include <sbl/hw/hal/gpio/handle.hpp>
#include <sbl/hw/reg/tim_basic.hpp>
#include <sbl/hw/reg/rcc.hpp>
#include <sbl/hw/reg/gpio.hpp>
#include <sbl/hw/reg/irq.hpp>
#include <sbl/hw/reg/cortex_m.hpp>

namespace sbl::driver {

class SoftPwm {
public:
    static constexpr uint8_t MAX_CHANNELS = 16;

    /**
     * @brief Register a GPIO pin as a BCM channel
     * @param handle GPIO handle (port, pin, active_low)
     * @return Channel index for use with set_duty()
     * @note Not ISR-safe — call before start()
     */
    static uint8_t add_channel(const sbl::GpioHandle& handle) {
        uint8_t idx = num_channels_;
        channels_[idx] = handle;

        // Track which ports are in use for efficient ISR
        uint8_t port = static_cast<uint8_t>(handle.port);
        bool found = false;
        for (uint8_t i = 0; i < num_ports_; ++i) {
            if (used_ports_[i] == port) { found = true; break; }
        }
        if (!found) {
            used_ports_[num_ports_++] = port;
        }

        ++num_channels_;
        return idx;
    }

    /**
     * @brief Set duty cycle for a channel (main-loop safe)
     *
     * Writes to pending buffer. Active buffer is swapped in ISR at bit 0.
     * @param channel Channel index from add_channel()
     * @param duty Duty cycle 0-255
     * @note ISR-safe — writes to pending buffer (double-buffered)
     */
    static void set_duty(uint8_t channel, uint8_t duty) {
        duty_pending_[channel] = duty;
        pending_dirty_ = true;
    }

    // Timer prescaler: 240 MHz APB1 timer / 240 = 1 MHz tick (1 us/count)
    static constexpr uint32_t TIM7_PSC = 239;

    // NVIC priority for BCM timer (below audio DMA at priority 4)
    static constexpr uint8_t BCM_IRQ_PRIORITY = 8;

    /**
     * @brief Start BCM engine (enables TIM7 + NVIC)
     *
     * Call after all channels are registered via add_channel().
     * TIM7 clock: APB1 timer = 240 MHz (post-init).
     * PSC = 239 -> 1 MHz tick. ARR = 3 -> 4 us for bit 0.
     * @note Not ISR-safe — init-time only
     */
    static void start() {
        using namespace sbl::hw::reg;

        // Enable TIM7 clock
        periph::rcc->APB1LENR |= RCC::APB1LENR_TIM7EN;
        volatile uint32_t dummy = periph::rcc->APB1LENR;
        (void)dummy;

        auto* tim = periph::tim7;

        tim->PSC = TIM7_PSC;
        tim->ARR = BASE_ARR;
        // Enable auto-reload preload so ARR changes take effect at next update
        tim->CR1 = TIM_Basic::CR1_ARPE;
        // Force update to load PSC and ARR
        tim->EGR = TIM_Basic::EGR_UG;
        // Clear the update flag generated by EGR_UG
        tim->SR = 0;
        // Enable update interrupt
        tim->DIER = TIM_Basic::DIER_UIE;

        // NVIC: enable TIM7 IRQ (position 55), below audio DMA priority
        constexpr auto irq = static_cast<int32_t>(IRQn::TIM7);
        periph::nvic->IP[irq] = (BCM_IRQ_PRIORITY << 4);
        periph::nvic->ISER[irq / 32] = (1u << (irq % 32));

        // Initialize active buffer to match pending
        for (uint8_t i = 0; i < num_channels_; ++i) {
            duty_active_[i] = duty_pending_[i];
        }

        bit_index_ = 0;

        // Enable counter
        tim->CR1 |= TIM_Basic::CR1_CEN;
    }

    /**
     * @brief TIM7 ISR — called from TIM7_IRQHandler
     *
     * Clears UIF, computes BSRR for each used port, advances bit index,
     * reloads ARR for next bit period.
     */
    static void irq_handler() {
        using namespace sbl::hw::reg;

        auto* tim = periph::tim7;

        // Clear update interrupt flag
        tim->SR = ~TIM_Basic::SR_UIF;

        // At bit 0 boundary: swap pending -> active if dirty
        if (bit_index_ == 0 && pending_dirty_) {
            for (uint8_t i = 0; i < num_channels_; ++i) {
                duty_active_[i] = duty_pending_[i];
            }
            pending_dirty_ = false;
        }

        uint8_t bit_mask = (1u << bit_index_);

        // For each port in use, compute a single BSRR word
        for (uint8_t p = 0; p < num_ports_; ++p) {
            uint32_t bsrr = 0;
            uint8_t port = used_ports_[p];

            for (uint8_t ch = 0; ch < num_channels_; ++ch) {
                if (static_cast<uint8_t>(channels_[ch].port) != port) continue;

                uint8_t pin = static_cast<uint8_t>(channels_[ch].pin);
                bool active_low = channels_[ch].active_low;

                // Should this channel be ON for this bit?
                bool on = (duty_active_[ch] & bit_mask) != 0;

                // Active-low: invert physical sense
                bool physical_high = active_low ? !on : on;

                if (physical_high) {
                    bsrr |= (1u << pin);         // BS — set
                } else {
                    bsrr |= (1u << (pin + 16));  // BR — reset
                }
            }

            // Single atomic BSRR write per port
            port_bsrr(port) = bsrr;
        }

        // Advance to next bit
        bit_index_ = (bit_index_ + 1) & 7;

        // Set ARR for next bit period: T * 2^bit_index
        tim->ARR = BASE_ARR << bit_index_;
    }

private:
    // T = 4 us at 1 MHz tick -> ARR = 3 (counts 0,1,2,3)
    static constexpr uint32_t BASE_ARR = 3;

    // Channel registration
    static inline sbl::GpioHandle channels_[MAX_CHANNELS] = {};
    static inline uint8_t num_channels_ = 0;

    // Port tracking for efficient ISR
    static inline uint8_t used_ports_[11] = {};  // Max 11 GPIO ports (A-K)
    static inline uint8_t num_ports_ = 0;

    // Double-buffered duty cycles
    static inline uint8_t duty_pending_[MAX_CHANNELS] = {};
    static inline volatile uint8_t duty_active_[MAX_CHANNELS] = {};
    static inline volatile bool pending_dirty_ = false;

    // Current BCM bit position (0-7)
    static inline volatile uint8_t bit_index_ = 0;

    // GPIO port layout: 0x400 spacing, BSRR at +0x18
    static constexpr uintptr_t GPIO_SPACING = 0x400;
    static constexpr uintptr_t BSRR_OFFSET  = 0x18;

    /**
     * @brief Get BSRR register reference for a GPIO port
     * Base address derived from SVD periph::gpioa (port 0)
     */
    static volatile uint32_t& port_bsrr(uint8_t port) {
        auto base = reinterpret_cast<uintptr_t>(sbl::hw::reg::periph::gpioa);
        auto addr = base + (port * GPIO_SPACING) + BSRR_OFFSET;
        return *reinterpret_cast<volatile uint32_t*>(addr);
    }
};

} // namespace sbl::driver

#endif // SBL_HW_DRIVER_SOFT_PWM_HPP_
