/**
 * @file timer_callback.hpp
 * @brief Single-callback periodic timer using TIM6
 *
 * Provides a guaranteed-rate callback via hardware timer interrupt.
 * TIM6 is a basic timer on APB1 (240 MHz timer clock post-init).
 * PSC = 239 → 1 MHz tick (1 us resolution). Max period = 65535 us (~65 ms).
 *
 * Runs at prio::kControlTick (level 8): below audio DMA (2) and USB/MIDI (4),
 * above debug UART (12).
 *
 * Usage:
 *   sbl::driver::TimerCallback::start(5000, my_callback);  // 200 Hz
 *   sbl::driver::TimerCallback::set_period(10000);          // 100 Hz
 *   sbl::driver::TimerCallback::stop();
 *
 * Requires timer_callback_irq.cpp compiled as direct app source.
 */
#ifndef SBL_HW_DRIVER_TIMER_CALLBACK_HPP_
#define SBL_HW_DRIVER_TIMER_CALLBACK_HPP_

#include <cstdint>
#include <sbl/hw/reg/tim_basic.hpp>
#include "priorities.hpp"
#include <sbl/hw/reg/rcc.hpp>
#include <sbl/hw/reg/irq.hpp>
#include <sbl/hw/reg/cortex_m.hpp>

namespace sbl::driver {

class TimerCallback {
public:
    using Callback = void(*)();

    /**
     * @brief Start periodic timer
     * @param period_us Period in microseconds (1–65535)
     * @param cb Function to call each period
     * @note Not ISR-safe — init-time only
     */
    static void start(uint32_t period_us, Callback cb) {
        using namespace sbl::hw::reg;

        s_callback = cb;

        // Enable TIM6 bus clock (APB1)
        periph::rcc->APB1LENR |= RCC::APB1LENR_TIM6EN;
        volatile uint32_t dummy = periph::rcc->APB1LENR;
        (void)dummy;

        auto* tim = periph::tim6;

        // APB1 timer clock = 240 MHz (2x multiplier when APB1 prescaler > 1)
        // PSC = 239 → 1 MHz tick (1 us/count)
        tim->PSC = 239;
        tim->ARR = period_us - 1;
        tim->CR1 = TIM_Basic::CR1_ARPE;

        // Force update to load PSC and ARR into shadow registers
        tim->EGR = TIM_Basic::EGR_UG;
        // Clear the update flag generated by EGR_UG
        tim->SR = 0;

        // Enable update interrupt
        tim->DIER = TIM_Basic::DIER_UIE;

        // NVIC: TIM6_DAC at the control-tick level (the BASEPRI ceiling)
        prio::enable_irq(IRQn::TIM6_DAC, prio::kControlTick);

        s_running = true;

        // Start counter
        tim->CR1 |= TIM_Basic::CR1_CEN;
    }

    /**
     * @brief Stop the timer and disable interrupt
     * @note ISR-safe — register writes
     */
    static void stop() {
        using namespace sbl::hw::reg;

        periph::tim6->CR1 &= ~TIM_Basic::CR1_CEN;
        periph::tim6->DIER = 0;
        s_running = false;
    }

    /**
     * @brief Change period without stopping
     * @param period_us New period in microseconds (1–65535)
     *
     * Takes effect at next update event (ARPE is enabled).
     * @note ISR-safe — single register write (ARPE buffered)
     */
    static void set_period(uint32_t period_us) {
        sbl::hw::reg::periph::tim6->ARR = period_us - 1;
    }

    /**
     * @brief ISR entry point — called from TIM6_DAC_IRQHandler
     */
    static void irq_handler() {
        using namespace sbl::hw::reg;

        // Clear update interrupt flag (rc_w0)
        periph::tim6->SR = ~TIM_Basic::SR_UIF;

        if (s_callback) {
            s_callback();
        }
    }

    /** @brief Check if timer is running
     *  @note ISR-safe — volatile read
     */
    static bool running() { return s_running; }

private:

    static inline Callback s_callback = nullptr;
    static inline volatile bool s_running = false;
};

} // namespace sbl::driver

#endif // SBL_HW_DRIVER_TIMER_CALLBACK_HPP_
