/**
 * @file irq.hpp
 * @brief STM32H750 IRQ number definitions
 *
 * MANUAL HEADER - Not generated by cecrops.
 *
 * Canonical source of truth for all STM32H750 interrupt numbers.
 * Referenced by startup.cpp (vector table), init.hpp (NVIC setup),
 * and sbl_usb_shim.h (TinyUSB compatibility).
 *
 * IRQ numbers from RM0433 Rev 8, Table 7 (Vector table).
 * Position = NVIC IRQ number (0-based, external interrupts only).
 * Cortex-M core exceptions are negative (not included here).
 */

#ifndef SBL_HW_REG_STM32H750_IRQ_HPP
#define SBL_HW_REG_STM32H750_IRQ_HPP

#include <cstdint>

namespace sbl::hw::reg {

/** STM32H750 external interrupt numbers (NVIC positions) */
enum class IRQn : int32_t {
    // Window watchdog
    WWDG                = 0,
    // PVD through EXTI
    PVD_AVD             = 1,
    // Tamper and timestamp
    TAMP_STAMP          = 2,
    // RTC wakeup
    RTC_WKUP            = 3,
    // Flash global
    FLASH               = 4,
    // RCC global
    RCC                 = 5,

    // External interrupts
    EXTI0               = 6,
    EXTI1               = 7,
    EXTI2               = 8,
    EXTI3               = 9,
    EXTI4               = 10,

    // DMA1 streams
    DMA1_Stream0        = 11,
    DMA1_Stream1        = 12,
    DMA1_Stream2        = 13,
    DMA1_Stream3        = 14,
    DMA1_Stream4        = 15,
    DMA1_Stream5        = 16,
    DMA1_Stream6        = 17,

    // ADC1 and ADC2 global
    ADC                 = 18,

    // FDCAN
    FDCAN1_IT0          = 19,
    FDCAN2_IT0          = 20,
    FDCAN1_IT1          = 21,
    FDCAN2_IT1          = 22,

    // External interrupts (continued)
    EXTI9_5             = 23,

    // Timers
    TIM1_BRK            = 24,
    TIM1_UP             = 25,
    TIM1_TRG_COM        = 26,
    TIM1_CC             = 27,
    TIM2                = 28,
    TIM3                = 29,
    TIM4                = 30,

    // I2C
    I2C1_EV             = 31,
    I2C1_ER             = 32,
    I2C2_EV             = 33,
    I2C2_ER             = 34,

    // SPI
    SPI1                = 35,
    SPI2                = 36,

    // USART
    USART1              = 37,
    USART2              = 38,
    USART3              = 39,

    // External interrupts (continued)
    EXTI15_10           = 40,

    // RTC alarm through EXTI
    RTC_Alarm           = 41,

    // Reserved: 42

    // Timers (continued)
    TIM8_BRK_TIM12      = 43,
    TIM8_UP_TIM13        = 44,
    TIM8_TRG_COM_TIM14   = 45,
    TIM8_CC              = 46,

    // DMA1 stream 7
    DMA1_Stream7         = 47,

    // FMC
    FMC                  = 48,

    // SDMMC1
    SDMMC1               = 49,

    // TIM5
    TIM5                 = 50,

    // SPI3
    SPI3                 = 51,

    // UART
    UART4                = 52,
    UART5                = 53,

    // TIM6 / DAC
    TIM6_DAC             = 54,

    // TIM7
    TIM7                 = 55,

    // DMA2 streams
    DMA2_Stream0         = 56,
    DMA2_Stream1         = 57,
    DMA2_Stream2         = 58,
    DMA2_Stream3         = 59,
    DMA2_Stream4         = 60,

    // Ethernet
    ETH                  = 61,
    ETH_WKUP             = 62,

    // FDCAN calibration
    FDCAN_CAL            = 63,

    // Reserved: 64-67

    // DMA2 streams (continued)
    DMA2_Stream5         = 68,
    DMA2_Stream6         = 69,
    DMA2_Stream7         = 70,

    // USART6
    USART6               = 71,

    // I2C3
    I2C3_EV              = 72,
    I2C3_ER              = 73,

    // USB1 OTG HS (0x40040000) - HS capable
    OTG_HS_EP1_OUT       = 74,
    OTG_HS_EP1_IN        = 75,
    OTG_HS_WKUP          = 76,
    OTG_HS               = 77,

    // DCMI
    DCMI                 = 78,

    // CRYP
    CRYP                 = 79,

    // HASH and RNG
    HASH_RNG             = 80,

    // FPU
    FPU                  = 81,

    // UART7, UART8
    UART7                = 82,
    UART8                = 83,

    // SPI4, SPI5, SPI6
    SPI4                 = 84,
    SPI5                 = 85,
    SPI6                 = 86,

    // SAI
    SAI1                 = 87,

    // LTDC
    LTDC                 = 88,
    LTDC_ER              = 89,

    // DMA2D
    DMA2D                = 90,

    // SAI2
    SAI2                 = 91,

    // QuadSPI
    QUADSPI              = 92,

    // LPTIM1
    LPTIM1               = 93,

    // HDMI-CEC
    CEC                  = 94,

    // I2C4
    I2C4_EV              = 95,
    I2C4_ER              = 96,

    // SPDIF-RX
    SPDIF_RX             = 97,

    // Reserved: 98-100

    // USB2 OTG FS (0x40080000) - FS only, used by Daisy Seed on PA11/PA12
    OTG_FS               = 101,

    // DMAMUX1 overrun
    DMAMUX1_OVR          = 102,

    // Reserved: 103-104

    // HRTIM
    HRTIM_Master         = 105,
    HRTIM_TIMA           = 106,
    HRTIM_TIMB           = 107,
    HRTIM_TIMC           = 108,
    HRTIM_TIMD           = 109,
    HRTIM_TIME           = 110,
    HRTIM_FLT            = 111,

    // DFSDM
    DFSDM_FLT0           = 112,
    DFSDM_FLT1           = 113,
    DFSDM_FLT2           = 114,
    DFSDM_FLT3           = 115,

    // SAI3
    SAI3                 = 116,

    // SWPMI
    SWPMI1               = 117,

    // TIM15, TIM16, TIM17
    TIM15                = 118,
    TIM16                = 119,
    TIM17                = 120,

    // MDIOS
    MDIOS_WKUP           = 121,
    MDIOS                = 122,

    // JPEG
    JPEG                 = 123,

    // MDMA
    MDMA                 = 124,

    // Reserved: 125

    // SDMMC2
    SDMMC2               = 126,

    // HSEM1
    HSEM1                = 127,

    // Reserved: 128

    // ADC3
    ADC3                 = 129,

    // DMAMUX2 overrun
    DMAMUX2_OVR          = 130,

    // BDMA channels
    BDMA_Channel0        = 131,
    BDMA_Channel1        = 132,
    BDMA_Channel2        = 133,
    BDMA_Channel3        = 134,
    BDMA_Channel4        = 135,
    BDMA_Channel5        = 136,
    BDMA_Channel6        = 137,
    BDMA_Channel7        = 138,

    // COMP
    COMP                 = 139,

    // LPTIM2, LPTIM3, LPTIM4, LPTIM5
    LPTIM2               = 140,
    LPTIM3               = 141,
    LPTIM4               = 142,
    LPTIM5               = 143,

    // LPUART1
    LPUART1              = 144,

    // Reserved: 145

    // CRS
    CRS                  = 146,

    // ECC
    ECC                  = 147,

    // SAI4
    SAI4                 = 148,

    // Reserved: 149

    // WKUP
    WAKEUP_PIN           = 150,
};

// Convenience: total number of external interrupts
inline constexpr uint32_t IRQ_COUNT = 151;

// Helper to get the raw integer value for NVIC register indexing
inline constexpr int32_t irq_num(IRQn irq) {
    return static_cast<int32_t>(irq);
}

} // namespace sbl::hw::reg

#endif // SBL_HW_REG_STM32H750_IRQ_HPP
