/**
 * @file tim_basic.hpp
 * @brief Register definitions for STM32H750 basic timers (TIM6/TIM7)
 *
 * MANUAL HEADER - Not generated by cecrops.
 * TIM6/TIM7 are basic upcounting timers with only 7 registers.
 *
 * Register offsets verified against RM0433 Rev 8, Section 46.4.
 */

#ifndef SBL_HW_REG_STM32H750_TIM_BASIC_HPP
#define SBL_HW_REG_STM32H750_TIM_BASIC_HPP

#include <cstdint>

namespace sbl::hw::reg {

/** TIM6/TIM7 basic timer register block */
struct TIM_Basic_t {
    volatile uint32_t CR1;    ///< 0x00 Control register 1
    volatile uint32_t CR2;    ///< 0x04 Control register 2
    uint32_t _reserved0;      ///< 0x08 (SMCR — not present on basic timers)
    volatile uint32_t DIER;   ///< 0x0C DMA/Interrupt enable register
    volatile uint32_t SR;     ///< 0x10 Status register
    volatile uint32_t EGR;    ///< 0x14 Event generation register
    uint32_t _reserved1[3];   ///< 0x18-0x20 (CCMR1/CCMR2/CCER gaps)
    volatile uint32_t CNT;    ///< 0x24 Counter
    volatile uint32_t PSC;    ///< 0x28 Prescaler
    volatile uint32_t ARR;    ///< 0x2C Auto-reload register
};

// CR1 fields
namespace TIM_Basic {
    inline constexpr uint32_t CR1_CEN   = (1U << 0);   ///< Counter enable
    inline constexpr uint32_t CR1_UDIS  = (1U << 1);   ///< Update disable
    inline constexpr uint32_t CR1_URS   = (1U << 2);   ///< Update request source
    inline constexpr uint32_t CR1_OPM   = (1U << 3);   ///< One-pulse mode
    inline constexpr uint32_t CR1_ARPE  = (1U << 7);   ///< Auto-reload preload enable

    // DIER fields
    inline constexpr uint32_t DIER_UIE  = (1U << 0);   ///< Update interrupt enable
    inline constexpr uint32_t DIER_UDE  = (1U << 8);   ///< Update DMA request enable

    // SR fields
    inline constexpr uint32_t SR_UIF    = (1U << 0);   ///< Update interrupt flag

    // EGR fields
    inline constexpr uint32_t EGR_UG    = (1U << 0);   ///< Update generation
}

// Peripheral instances
namespace periph {
    inline auto* const tim6 = reinterpret_cast<TIM_Basic_t*>(0x40001000);
    inline auto* const tim7 = reinterpret_cast<TIM_Basic_t*>(0x40001400);
}

} // namespace sbl::hw::reg

#endif // SBL_HW_REG_STM32H750_TIM_BASIC_HPP
