/**
 * @file usb_otg.hpp
 * @brief STM32H750 USB OTG (DWC2) register definitions
 *
 * MANUAL HEADER - Not generated by cecrops.
 *
 * Why manual: The STM32H7 SVD represents USB OTG device endpoints as 8
 * individually-named register groups with independently specified offsets.
 * The offsets for endpoints 5-7 are wrong — registers appear out of order
 * in the generated struct. This is a structural SVD defect, not a simple
 * errata fix. The hardware has a repeating 0x20-byte stride per endpoint,
 * but the SVD doesn't model it that way.
 *
 * Register layout derived from:
 *   - STM32H750 Reference Manual RM0433, Chapter 60 (USB OTG)
 *   - Synopsys DWC2 programming guide
 *   - TinyUSB dwc2_type.h (BSD licensed) for offset verification
 *
 * STM32H750 has two USB OTG controllers:
 *   - USB1_OTG_HS at 0x40040000 (HS with ULPI or FS with internal PHY)
 *   - USB2_OTG_FS at 0x40080000 (FS only with internal PHY)
 *   - Both have 9 endpoints (EP0-EP8) and 4096-byte FIFOs
 *   - Daisy Seed uses USB2_OTG_FS on PA11/PA12
 */

#ifndef SBL_HW_REG_STM32H750_USB_OTG_HPP
#define SBL_HW_REG_STM32H750_USB_OTG_HPP

#include <cstdint>

namespace sbl::hw::reg {

// ============================================================================
// Global Registers (base + 0x000)
// ============================================================================

struct OTG_Global_t {
    volatile uint32_t GOTGCTL;       // 0x000 OTG control and status
    volatile uint32_t GOTGINT;       // 0x004 OTG interrupt
    volatile uint32_t GAHBCFG;       // 0x008 AHB configuration
    volatile uint32_t GUSBCFG;       // 0x00C USB configuration
    volatile uint32_t GRSTCTL;       // 0x010 Reset control
    volatile uint32_t GINTSTS;       // 0x014 Core interrupt status
    volatile uint32_t GINTMSK;       // 0x018 Core interrupt mask
    volatile uint32_t GRXSTSR;       // 0x01C Receive status debug read
    volatile uint32_t GRXSTSP;       // 0x020 Receive status read/pop
    volatile uint32_t GRXFSIZ;       // 0x024 Receive FIFO size
    volatile uint32_t DIEPTXF0;      // 0x028 EP0 TX FIFO size (device) / GNPTXFSIZ (host)
    volatile uint32_t GNPTXSTS;      // 0x02C Non-periodic TX FIFO/queue status
    volatile uint32_t GI2CCTL;       // 0x030 I2C access
    volatile uint32_t GPVNDCTL;      // 0x034 PHY vendor control
    volatile uint32_t GCCFG;         // 0x038 General core configuration
    volatile uint32_t CID;           // 0x03C Core ID
    volatile uint32_t GSNPSID;       // 0x040 Synopsys ID
    volatile uint32_t GHWCFG1;       // 0x044 Hardware configuration 1
    volatile uint32_t GHWCFG2;       // 0x048 Hardware configuration 2
    volatile uint32_t GHWCFG3;       // 0x04C Hardware configuration 3
    volatile uint32_t GHWCFG4;       // 0x050 Hardware configuration 4
    volatile uint32_t GLPMCFG;       // 0x054 LPM configuration
    volatile uint32_t GPWRDN;        // 0x058 Power down
    volatile uint32_t GDFIFOCFG;     // 0x05C DFIFO software config
    volatile uint32_t GADPCTL;       // 0x060 ADP timer control
    uint8_t _reserved0[0x9C];       // 0x064-0x0FF
    volatile uint32_t HPTXFSIZ;      // 0x100 Host periodic TX FIFO size
    volatile uint32_t DIEPTXF[7];    // 0x104-0x11F EP1-7 TX FIFO sizes
};

static_assert(sizeof(OTG_Global_t) == 0x120, "OTG_Global_t size mismatch");

// ============================================================================
// Device Registers (base + 0x800)
// ============================================================================

struct OTG_Device_t {
    volatile uint32_t DCFG;          // 0x800 Device configuration
    volatile uint32_t DCTL;          // 0x804 Device control
    volatile uint32_t DSTS;          // 0x808 Device status (read-only)
    uint32_t _reserved0;             // 0x80C
    volatile uint32_t DIEPMSK;       // 0x810 Device IN EP common interrupt mask
    volatile uint32_t DOEPMSK;       // 0x814 Device OUT EP common interrupt mask
    volatile uint32_t DAINT;         // 0x818 Device all endpoints interrupt
    volatile uint32_t DAINTMSK;      // 0x81C Device all endpoints interrupt mask
    uint32_t _reserved1[2];          // 0x820-0x827
    volatile uint32_t DVBUSDIS;      // 0x828 Device VBUS discharge time
    volatile uint32_t DVBUSPULSE;    // 0x82C Device VBUS pulsing time
    volatile uint32_t DTHRCTL;       // 0x830 Device threshold control
    volatile uint32_t DIEPEMPMSK;    // 0x834 Device IN EP FIFO empty interrupt mask
    volatile uint32_t DEACHINT;      // 0x838 Device each EP interrupt
    volatile uint32_t DEACHINTMSK;   // 0x83C Device each EP interrupt mask
};

// ============================================================================
// Endpoint Registers (stride = 0x20 per endpoint)
// ============================================================================

/** IN endpoint register block (base + 0x900 + n*0x20) */
struct OTG_INEndpoint_t {
    volatile uint32_t DIEPCTL;       // +0x00 Endpoint control
    uint32_t _reserved0;             // +0x04
    volatile uint32_t DIEPINT;       // +0x08 Endpoint interrupt
    uint32_t _reserved1;             // +0x0C
    volatile uint32_t DIEPTSIZ;      // +0x10 Transfer size
    volatile uint32_t DIEPDMA;       // +0x14 DMA address
    volatile uint32_t DTXFSTS;       // +0x18 TX FIFO status (read-only)
    uint32_t _reserved2;             // +0x1C
};

static_assert(sizeof(OTG_INEndpoint_t) == 0x20, "OTG_INEndpoint_t must be 0x20 bytes");

/** OUT endpoint register block (base + 0xB00 + n*0x20) */
struct OTG_OUTEndpoint_t {
    volatile uint32_t DOEPCTL;       // +0x00 Endpoint control
    uint32_t _reserved0;             // +0x04
    volatile uint32_t DOEPINT;       // +0x08 Endpoint interrupt
    uint32_t _reserved1;             // +0x0C
    volatile uint32_t DOEPTSIZ;      // +0x10 Transfer size
    volatile uint32_t DOEPDMA;       // +0x14 DMA address
    uint32_t _reserved2[2];          // +0x18-0x1F
};

static_assert(sizeof(OTG_OUTEndpoint_t) == 0x20, "OTG_OUTEndpoint_t must be 0x20 bytes");

// ============================================================================
// Power and Clock Gating (base + 0xE00)
// ============================================================================

struct OTG_PCGCCTL_t {
    volatile uint32_t PCGCCTL;       // 0xE00 Power and clock gating control
    volatile uint32_t PCGCCTL1;      // 0xE04 Power and clock gating control 1
};

// ============================================================================
// Composite Register Map
//
// Maps the full DWC2 register space as a single struct for offset verification.
// Individual sub-blocks are also accessible via periph:: pointers below.
// ============================================================================

struct OTG_t {
    OTG_Global_t global;             // 0x000-0x11F
    uint8_t _reserved_host[0x6E0];   // 0x120-0x7FF (host registers, not modeled)
    OTG_Device_t device;             // 0x800-0x83F
    uint8_t _reserved_eachmsk[0xC0]; // 0x840-0x8FF (per-EP masks)
    OTG_INEndpoint_t epin[9];        // 0x900-0xA1F (9 endpoints on STM32H750)
    uint8_t _reserved_epin[0xE0];    // 0xA20-0xAFF
    OTG_OUTEndpoint_t epout[9];      // 0xB00-0xC1F (9 endpoints on STM32H750)
    uint8_t _reserved_epout[0xE0];   // 0xC20-0xCFF
    uint8_t _reserved_d[0x100];      // 0xD00-0xDFF
    OTG_PCGCCTL_t pcgcctl;           // 0xE00-0xE07
};

// ============================================================================
// GCCFG bit definitions (General Core Configuration)
// ============================================================================

namespace GCCFG {
    inline constexpr uint32_t PWRDWN_Pos   = 16;
    inline constexpr uint32_t PWRDWN       = (1u << 16);  // Power down / enable internal FS PHY
    inline constexpr uint32_t VBDEN_Pos    = 21;
    inline constexpr uint32_t VBDEN        = (1u << 21);  // VBUS detection enable
}

// ============================================================================
// GOTGCTL bit definitions (OTG Control and Status)
// ============================================================================

namespace GOTGCTL {
    inline constexpr uint32_t BVALOEN_Pos  = 6;
    inline constexpr uint32_t BVALOEN      = (1u << 6);   // B-session valid override enable
    inline constexpr uint32_t BVALOVAL_Pos = 7;
    inline constexpr uint32_t BVALOVAL     = (1u << 7);   // B-session valid override value
}

// ============================================================================
// GUSBCFG bit definitions (USB Configuration)
// ============================================================================

namespace GUSBCFG {
    inline constexpr uint32_t TOCAL_Pos    = 0;
    inline constexpr uint32_t TOCAL_Msk    = (0x7u << 0);  // FS timeout calibration
    inline constexpr uint32_t PHYSEL_Pos   = 6;
    inline constexpr uint32_t PHYSEL       = (1u << 6);    // USB 2.0 HS PHY / FS serial
    inline constexpr uint32_t TRDT_Pos     = 10;
    inline constexpr uint32_t TRDT_Msk     = (0xFu << 10); // USB turnaround time
    inline constexpr uint32_t FHMOD_Pos    = 29;
    inline constexpr uint32_t FHMOD        = (1u << 29);   // Force host mode
    inline constexpr uint32_t FDMOD_Pos    = 30;
    inline constexpr uint32_t FDMOD        = (1u << 30);   // Force device mode
}

// ============================================================================
// GAHBCFG bit definitions (AHB Configuration)
// ============================================================================

namespace GAHBCFG {
    inline constexpr uint32_t GINTMSK_Pos  = 0;
    inline constexpr uint32_t GINTMSK      = (1u << 0);   // Global interrupt mask
    inline constexpr uint32_t TXFELVL_Pos  = 7;
    inline constexpr uint32_t TXFELVL      = (1u << 7);   // TX FIFO empty level
}

// ============================================================================
// GRSTCTL bit definitions (Reset Control)
// ============================================================================

namespace GRSTCTL {
    inline constexpr uint32_t CSRST_Pos    = 0;
    inline constexpr uint32_t CSRST        = (1u << 0);   // Core soft reset
    inline constexpr uint32_t TXFFLSH_Pos  = 5;
    inline constexpr uint32_t TXFFLSH      = (1u << 5);   // TX FIFO flush
    inline constexpr uint32_t RXFFLSH_Pos  = 4;
    inline constexpr uint32_t RXFFLSH      = (1u << 4);   // RX FIFO flush
    inline constexpr uint32_t TXFNUM_Pos   = 6;
    inline constexpr uint32_t TXFNUM_Msk   = (0x1Fu << 6); // TX FIFO number
    inline constexpr uint32_t AHBIDL_Pos   = 31;
    inline constexpr uint32_t AHBIDL       = (1u << 31);  // AHB master idle
}

// ============================================================================
// DEPCTL bit definitions (shared IN/OUT endpoint control)
// ============================================================================

namespace DEPCTL {
    inline constexpr uint32_t MPS_Pos      = 0;
    inline constexpr uint32_t MPS_Msk      = 0x7FFu;      // Maximum packet size
    inline constexpr uint32_t USBAEP_Pos   = 15;
    inline constexpr uint32_t USBAEP       = (1u << 15);   // USB active endpoint
    inline constexpr uint32_t NAKSTS_Pos   = 17;
    inline constexpr uint32_t NAKSTS       = (1u << 17);   // NAK status
    inline constexpr uint32_t EPTYP_Pos    = 18;
    inline constexpr uint32_t EPTYP_Msk    = (0x3u << 18); // Endpoint type
    inline constexpr uint32_t STALL_Pos    = 21;
    inline constexpr uint32_t STALL        = (1u << 21);   // STALL handshake
    inline constexpr uint32_t CNAK_Pos     = 26;
    inline constexpr uint32_t CNAK         = (1u << 26);   // Clear NAK
    inline constexpr uint32_t SNAK_Pos     = 27;
    inline constexpr uint32_t SNAK         = (1u << 27);   // Set NAK
    inline constexpr uint32_t EPDIS_Pos    = 30;
    inline constexpr uint32_t EPDIS        = (1u << 30);   // Endpoint disable
    inline constexpr uint32_t EPENA_Pos    = 31;
    inline constexpr uint32_t EPENA        = (1u << 31);   // Endpoint enable
}

// ============================================================================
// PCGCCTL bit definitions (Power and Clock Gating)
// ============================================================================

namespace PCGCCTL {
    inline constexpr uint32_t STPPCLK_Pos  = 0;
    inline constexpr uint32_t STPPCLK      = (1u << 0);   // Stop PHY clock
    inline constexpr uint32_t GATEHCLK_Pos = 1;
    inline constexpr uint32_t GATEHCLK     = (1u << 1);   // Gate HCLK
    inline constexpr uint32_t PHYSUSP_Pos  = 4;
    inline constexpr uint32_t PHYSUSP      = (1u << 4);   // PHY suspended
}

// ============================================================================
// Peripheral Instances
// ============================================================================

namespace periph {
    // USB1_OTG_HS (0x40040000) - HS capable, not used on Daisy Seed LQFP100
    inline auto* const usb1_otg    = reinterpret_cast<OTG_t*>(0x40040000);
    inline auto* const usb1_global = reinterpret_cast<OTG_Global_t*>(0x40040000);
    inline auto* const usb1_device = reinterpret_cast<OTG_Device_t*>(0x40040800);
    inline auto* const usb1_pcgcctl = reinterpret_cast<OTG_PCGCCTL_t*>(0x40040E00);

    // USB2_OTG_FS (0x40080000) - FS only, used by Daisy Seed on PA11/PA12
    inline auto* const usb2_otg    = reinterpret_cast<OTG_t*>(0x40080000);
    inline auto* const usb2_global = reinterpret_cast<OTG_Global_t*>(0x40080000);
    inline auto* const usb2_device = reinterpret_cast<OTG_Device_t*>(0x40080800);
    inline auto* const usb2_pcgcctl = reinterpret_cast<OTG_PCGCCTL_t*>(0x40080E00);
}

} // namespace sbl::hw::reg

#endif // SBL_HW_REG_STM32H750_USB_OTG_HPP
